@echo off                        
echo %BOLD%%FW%                                .@'
echo %BOLD%%FY%  I~\ I   I  I I /` %FW%          .@@@:
echo %BOLD%%FY%  I_/ I   I  I I{   %FW%        .;@@@::::.%RS%%FY%..%BOLD%%FW%  .
echo %BOLD%%FY%  I   I__  \_I I \. %FW%       .;@@::::::::::::
echo                            :@@@{::::::::::: 
echo                            :@@:``  %RS%%FY% ::%BOLD%%FW%`':: 
echo                             :@     %RS%%FY%::%BOLD%%FW%   '
echo                                    %RS%%FY%::
echo %BOLD%%FY%       I~\ I~\  /\  I~\  I  I  /~\%RS%%FY%::%BOLD%/~I~\ I  /\  I  I /~~
echo %BOLD%%FY%       I_/ I_/ I  I I  I I  I I   %RS%%FY%::%BOLD%  I   I I  I I\ I ~-.
echo %BOLD%%FY%       I   I \  \/  I_/   \_I  \_/%RS%%FY%::%BOLD%  I   I  \/  I `I __/
echo %RS%%FY%                                  ::.
echo                                   :::

